language: csharp
solution: Elurnity.Serialization.sln
install:
  - nuget restore Elurnity.Serialization.sln
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Elurnity.Serialization.sln
  - mono ./testrunner/NUnit.ConsoleRunner*/tools/nunit3-console.exe ./*/bin/Release/*Tests.dll
